spring.application.name=AuthService
server.port=8082
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#spring.application.name=Auth-Service

spring.datasource.url=jdbc:postgresql://localhost:5432/authservice
spring.datasource.password=root
spring.datasource.username=postgres
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

hibernate.jdbc.batch_size=20
hibernate.order_inserts=true

jwt.secret=4f1575ed212e9b1698f7e8cc584f3ba47ec78ee8a29018c75b41d699a573a2d